sudo: required
os: linux
language: cpp

script:
  - ./buildcoverage.sh
  - ./cppcheck.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - george-edison55-precise-backports
    packages:
      - g++
      - cmake-data
      - cmake
      - libboost-all-dev
      - libevent-dev
      - libdouble-conversion-dev
      - libgoogle-glog-dev
      - libgflags-dev
      - libiberty-dev
      - liblz4-dev
      - liblzma-dev
      - libsnappy-dev
      - make
      - zlib1g-dev
      - binutils-dev
      - libjemalloc-dev
      - libssl-dev
      - pkg-config
      - libunwind8-dev
      - libelf-dev
      - libdwarf-dev