language: cpp
compiler: gcc
os: linux
before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
script:
  - bash ./build.sh
addons:
  apt:
    packages:
      - cmake
      - libgflags-dev
      - libgflags2
      - libgoogle-glog-dev
      - valgrind
    sources:
      - kalakris-cmake