sudo: required
language: cpp
compiler: clang
os: linux
services:
  - docker
# Fedora supports the libraries.
before_install:
  - docker pull fedora:latest
  - docker ps -a
  - docker run fedora:latest /bin/sh -c "cd /root; yes | dnf install git cmake clang gflags-devel glog-devel valgrind; git clone https://github.com/tdauth/cpp-futures-promises.git; cd ./cpp-futures-promises; bash ./build.sh"

#script:
#  - bash ./build.sh
#addons:
#  apt:
#    packages:
#      - cmake
#      - libgflags-dev
#      - libgflags2
#      - libgoogle-glog-dev
#      - valgrind
#      - clang
#    sources:
#      - kalakris-cmake