language: cpp
compiler:
- gcc
os:
- linux
script:
  - bash ./build.sh
addons:
  apt:
    packages:
      - cmake
      - gcc
      - libgflags-dev
      - libgflags2
      - libgoogle-glog-dev
      - valgrind
    sources:
      - kalakris-cmake