language: cpp
compiler: gcc
os: linux
script:
  - bash ./build.sh
addons:
  apt:
    packages:
      - cmake
      - libgflags-dev
      - libgflags2
      - libgoogle-glog-dev
      - valgrind
      - chrpath
      - patchelf
    sources:
      - kalakris-cmake