dist: xenial
sudo: required
os: linux
language: cpp

script:
  - # Link gcc-6 and g++-6 to their standard commands
  - sudo ln -sf /usr/bin/gcc-6 /usr/bin/gcc
  - sudo ln -sf /usr/bin/g++-6 /usr/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v
  - bash ./buildcoverage.sh
  - bash ./cppcheck.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - george-edison55-precise-backports
    update: true
    packages:
      - g++-6
      - cmake-data
      - cmake
      - libboost-all-dev
      - libevent-dev
      - libdouble-conversion-dev
      - libgoogle-glog-dev
      - libgflags-dev
      - libiberty-dev
      - liblz4-dev
      - liblzma-dev
      - libsnappy-dev
      - make
      - zlib1g-dev
      - binutils-dev
      - libjemalloc-dev
      - libssl-dev
      - pkg-config
      - libunwind8-dev
      - libelf-dev
      - libdwarf-dev
      - valgrind